#!/bin/bash
rm -f data/com/*
rm -f data/com/monomerA/*
rm -f data/com/monomerB/*
rm -f data/cnf/*
rm -f data/cnf/monomerA/*
rm -f data/cnf/monomerB/*
rm -f data/out/monomerA/*
rm -f data/out/monomerB/*
rm -f data/log/*
rm -f data/log/monomerA/*
rm -f data/log/monomerB/*
