#!/bin/bash
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --output=data/out/BLIND01691.out
#SBATCH --mem-per-cpu=2GB
# This is a template for running com Gaussian jobs
# Set environment variables for Gaussian
source $HOME/.g09

# Directory where the work Guassian will be done and the source directory 
wrkdir=/scratch/local/$USER/BLIND01691
srcdir=$w

# Make a temporary work directory
mkdir -p $wrkdir
cd $wrkdir

# Copy basis functions for calculating to work 
cp $srcdir/data/gbs/* .
# Copy parameters for M05 functional
cp ${srcdir}/data/dat/param/ParamM05* .
#cp ${srcdir}/data/temp/ParamrPW86.dat .
# Copy Gaussian input file 
cp ${srcdir}/data/com/BLIND01691.com .

# Run Gaussian
${g09root}/g09/g09 < BLIND01691.com > ${srcdir}/data/log/BLIND01691.log

# Remove scratch
rm -rf $wrkdir

