#!/bin/bash
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --output=data/slurm/BLIND_dimer02446.out
#SBATCH --mem-per-cpu=2GB
# This is a template for running orca jobs


# Directory where the work Guassian will be done and the source directory 
wrkdir=/scratch/local/$USER/BLIND_dimer02446

# Make a temporary work directory
mkdir -p $wrkdir
cd $wrkdir

cp "$w"/data/orca/BLIND_dimer02446.inp .

# Run Orca
"$orca"/orca BLIND_dimer02446.inp > "$w"/data/orca/BLIND_dimer02446.out

# Remove scratch
rm -rf $wrkdir

