#!/bin/bash
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --output=data/slurm/CH4_dimer01243.out
#SBATCH --mem-per-cpu=2GB
# This is a template for running orca jobs


# Directory where the work Guassian will be done and the source directory 
wrkdir=/scratch/local/$USER/CH4_dimer01243

# Make a temporary work directory
mkdir -p $wrkdir
cd $wrkdir

cp "$w"/data/orca/CH4_dimer01243.inp .

# Run Orca
"$orca"/orca CH4_dimer01243.inp > "$w"/data/orca/CH4_dimer01243.out

# Remove scratch
rm -rf $wrkdir

