#!/bin/bash
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --output=data/slurm/orca/CH4_dimer02140.out
#SBATCH --mem-per-cpu=2GB
# This is a template for running orca jobs

export $orca
export $w

# Directory where the work Guassian will be done and the source directory 
wrkdir=/scratch/local/$USER/CH4_dimer02140

# Make a temporary work directory
mkdir -p $wrkdir
cd $wrkdir

cp "$w"data/orca/CH4_dimer02140.inp .

# Run Orca
"$orca"orca CH4_dimer02140.inp > "$w"data/orca/CH4_dimer02140.out

# Remove scratch
rm -rf $wrkdir

